### ISSUE TITLE
ImportError: cannot import name __version__

### ISSUE THREAD

**Issue by johnsaigle** [bndr/pipreqs#130] opened 2018-08-28 19:03 UTC
Tried to install this packaged via

```
pip3 install pipreqs
```

which succeeded without error. However, I am unable to run it from the command line or import the library via the Python interpreter. In both cases I get the traceback below:

```
Python 3.5.3 (default, Jan 19 2017, 14:11:04) 
[GCC 6.3.0 20170118] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pipreqs
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/users/me/.local/lib/python3.5/site-packages/pipreqs/pipreqs.py", line 37, in <module>
    from pipreqs import __version__
ImportError: cannot import name '__version__'
```

### Environment info

* Python 3.5.3

#### Output of `uname -a`
```
Linux ace-ws-15 4.9.0-6-amd64 #1 SMP Debian 4.9.88-1+deb9u1 (2018-05-07) x86_64 GNU/Linux
```

**Comment by jonafato** [comment] 2018-11-09 03:40
I can't seem to reproduce this issue. Do you still see this behavior?

**Comment by AlexAshs** [comment] 2019-09-06 14:34
Hi @jonafato ,
this issue occurred to me today.

**Output of uname -a**

Linux Blade 4.19.69-1-MANJARO #1 SMP PREEMPT Thu Aug 29 08:51:46 UTC 2019 x86_64 GNU/Linux

I when I had a look at the import statement `from pipreqs import __version__`, I couldn't find a file named "__version__"

**Comment by alan-barzilay** [comment] 2021-05-09 04:38
I also can't reproduce this error so I'm closing it. Feel free to reopen it if you have any new information or if you can provide a minimum setup to reproduce it

**Closed by alan-barzilay** 2021-05-09 04:38 UTC

**Comment by aboutmydreams** [comment] 2021-05-14 19:00
same problem
python 3.8.4
pipreqs 0.4.10


----> 1 import pipreqs
~/Library/Python/3.8/lib/python/site-packages/pipreqs/pipreqs.py in <module>
     48 from yarg.exceptions import HTTPError
     49
  git
---> 50 from pipreqs import __version__
     51
     52 REGEXP = [

ImportError: cannot import name '__version__' from partially initialized module 'pipreqs' (most likely due to a circular import) (/Users/a/Library/Python/3.8/lib/python/site-packages/pipreqs/pipreqs.py)

**Comment by alan-barzilay** [comment] 2021-05-15 16:53
/_/_version__ is defined in the /_/_init__.py file, this may explain the partially initialized part of the error message. Could you provide a minimal setup for reproducing this error?
Also, pipreqs was originally intended to be used as a module, not as an import so this is probably an artifact of that

**Comment by DJJBanx** [comment] 2021-06-10 00:49
I ran into the same issue because I was running the pipreqs.py file from site-packages to avoid adding it to path on windows. I called the file directly and it could not find __version__.

A fix for this is to edit the __init__.py file in the site-packages and copy all of the code defining __author__, __email__, and __version__ 
```
__author__ = 'Vadim Kravcenko'
__email__ = 'vadim.kravcenko@gmail.com'
__version__ = '0.4.10'
```

and paste it into the pipreqs.py file in place of 
```
from pipreqs import __version__
```
On line 50. (Removing that import statement and defining the version in the file itself)

**Comment by ldaher** [comment] 2021-12-02 14:27
Although the question is a little bit old, I still consider relevant since I've faced the exactly same problem and the solution I found was to downgrade the "pipreqs" module to 0.4.8.

Btw... my scenario is different than presented here... 
The python version is 2.7.18 and according to the "History" session within "pipreqs" website (https://pypi.org/project/pipreqs) I've decided to teste version 0.4.8 based on the release date.

**Comment by kevinlakhani** [comment] 2021-12-12 08:27
I also have run into this problem on both Python 3.8 and 3.9. Could not even install pipreqs with `pip3 install pipreqs`:
```
WARNING: Value for scheme.platlib does not match. Please report this to <https://github.com/pypa/pip/issues/10151>
distutils: /var/data/python/lib/python3.9/site-packages
sysconfig: /home/kevin/.local/lib/python3.9/site-packages
WARNING: Value for scheme.purelib does not match. Please report this to <https://github.com/pypa/pip/issues/10151>
distutils: /var/data/python/lib/python3.9/site-packages
sysconfig: /home/kevin/.local/lib/python3.9/site-packages
WARNING: Value for scheme.headers does not match. Please report this to <https://github.com/pypa/pip/issues/10151>
distutils: /var/data/python/include/python3.9/UNKNOWN
sysconfig: /home/kevin/.local/include/python3.9/UNKNOWN
WARNING: Value for scheme.scripts does not match. Please report this to <https://github.com/pypa/pip/issues/10151>
distutils: /var/data/python/bin
sysconfig: /home/kevin/.local/bin
WARNING: Value for scheme.data does not match. Please report this to <https://github.com/pypa/pip/issues/10151>
distutils: /var/data/python
sysconfig: /home/kevin/.local
WARNING: Additional context:
user = True
home = None
root = None
prefix = None
```

Installing 0.4.8 with `pip install --user pipreqs==0.4.8` worked
