### ISSUE TITLE
whitelines at the beginning of the file

### ISSUE THREAD

**Issue by EliasVansteenkiste** [bndr/pipreqs#193] opened 2020-02-24 15:48 UTC
pipreqs fails on python files which have blank lines at the beginning of the file.

System:
- Python 3.6.8
- 16.04.1-Ubuntu
- pipreqs 0.4.10

Stacktrace:
```
ERROR: Failed on file: /home/test/file.py
Traceback (most recent call last):
  File "/usr/local/bin/pipreqs", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/pipreqs/pipreqs.py", line 470, in main
    init(args)
  File "/usr/local/lib/python3.6/dist-packages/pipreqs/pipreqs.py", line 409, in init
    follow_links=follow_links)
  File "/usr/local/lib/python3.6/dist-packages/pipreqs/pipreqs.py", line 138, in get_all_imports
    raise exc
  File "/usr/local/lib/python3.6/dist-packages/pipreqs/pipreqs.py", line 124, in get_all_imports
    tree = ast.parse(contents)
  File "/usr/lib/python3.6/ast.py", line 35, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)
  File "<unknown>", line 1
    ﻿
    ^
SyntaxError: invalid character in identifier
```

**Comment by jonafato** [comment] 2020-03-28 03:46
I can't reproduce this. Syntax errors with `pipreqs` tend to come from using `pipreqs` installed to a different version of Python than the target source files use. Can you provide a minimal example of the issue here along with relevant Python version information (what version the source code is intended for, what environment `pipreqs` is installed to)?

**Comment by lingdavid** [comment] 2020-03-31 09:53
I also encountered this problem, did you solve it? @jonafato 
`SyntaxError: invalid character in identifier`

**Comment by jonafato** [comment] 2020-03-31 16:06
@lingdavid Can you provide a minimal example that causes this error?

**Comment by renaudl** [comment] 2020-09-07 09:52
Try recreating the file. Worked for me in pycharm copy / paste without formatting.

**Comment by zhang14725804** [comment] 2020-12-16 07:04
`PS E:\QzoneExporter> pipreqs ./ --encoding='utf8' --force
ERROR: Failed on file: ./exporter.py
Traceback (most recent call last):
  File "c:\users\xiaohu\appdata\local\programs\python\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\xiaohu\appdata\local\programs\python\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\xiaohu\AppData\Local\Programs\Python\Python37\Scripts\pipreqs.exe\__main__.py", line 9, in <module>
  File "c:\users\xiaohu\appdata\local\programs\python\python37\lib\site-packages\pipreqs\pipreqs.py", line 470, in main
    init(args)
  File "c:\users\xiaohu\appdata\local\programs\python\python37\lib\site-packages\pipreqs\pipreqs.py", line 409, in init
    follow_links=follow_links)
  File "c:\users\xiaohu\appdata\local\programs\python\python37\lib\site-packages\pipreqs\pipreqs.py", line 138, in get_all_imports
    raise exc
  File "c:\users\xiaohu\appdata\local\programs\python\python37\lib\site-packages\pipreqs\pipreqs.py", line 124, in get_all_imports
    tree = ast.parse(contents)
  File "c:\users\xiaohu\appdata\local\programs\python\python37\lib\ast.py", line 35, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)
  File "<unknown>", line 1
    ﻿import argparse
          ^
SyntaxError: invalid character in identifier`

**Comment by zhang14725804** [comment] 2020-12-16 07:05
> PS E:\QzoneExporter> pipreqs ./ --encoding='utf8' --force
ERROR: Failed on file: ./exporter.py
Traceback (most recent call last):
  File "c:\users\xiaohu\appdata\local\programs\python\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\xiaohu\appdata\local\programs\python\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\xiaohu\AppData\Local\Programs\Python\Python37\Scripts\pipreqs.exe\__main__.py", line 9, in <module>
  File "c:\users\xiaohu\appdata\local\programs\python\python37\lib\site-packages\pipreqs\pipreqs.py", line 470, in main
    init(args)
  File "c:\users\xiaohu\appdata\local\programs\python\python37\lib\site-packages\pipreqs\pipreqs.py", line 409, in init
    follow_links=follow_links)
  File "c:\users\xiaohu\appdata\local\programs\python\python37\lib\site-packages\pipreqs\pipreqs.py", line 138, in get_all_imports
    raise exc
  File "c:\users\xiaohu\appdata\local\programs\python\python37\lib\site-packages\pipreqs\pipreqs.py", line 124, in get_all_imports
    tree = ast.parse(contents)
  File "c:\users\xiaohu\appdata\local\programs\python\python37\lib\ast.py", line 35, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)
  File "<unknown>", line 1
    ﻿import argparse
          ^
SyntaxError: invalid character in identifier

**Comment by alan-barzilay** [comment] 2021-03-28 15:41
I'm closing the issue since we weren't able to reproduce it. Feel free to reopen it with a minimal example that reproduces this error.

**Closed by alan-barzilay** 2021-03-28 15:41 UTC

**Comment by Mentalistt** [comment] 2021-06-23 08:44
I received the same error when I run pipreqs --encoding=iso-8859-1
........
packages/pipreqs/pipreqs.py", line 124, in get_all_imports
    tree = ast.parse(contents)
  File "/usr/lib/python3.8/ast.py", line 47, in parse
    return compile(source, filename, mode, flags,
  File "<unknown>", line 1
    ï»¿#------------------------------------------------------------------------------
      ^
SyntaxError: invalid character in identifier

**Comment by alan-barzilay** [comment] 2021-06-23 16:19
please provide a minimal example to reproduce this
