### ISSUE TITLE
Clash with findpackages

### ISSUE THREAD

**Issue by bluprince13** [bndr/pipreqs#91] opened 2017-10-18 20:13 UTC
I'm using the findpackages packages to list my packages in config.py

`packages=find_packages(exclude=['docs', 'tests']),`

pipreqs results in an error:

```
  File "<unknown>", line 9
    packages=packages=['noise'],
                     ^
SyntaxError: invalid syntax
```

**Comment by jonafato** [comment] 2017-10-20 17:41
The error posted doesn't seem to relate to `find_packages`. Please post the full error message and a minimal example that reproducibly causes `pipreqs` to fail.

**Comment by bluprince13** [comment] 2017-10-20 18:22
Yes, I tried this today without find_packages and the error persisted. I will post a minimal example soon.

**Comment by jonafato** [comment] 2017-10-20 19:44
Based on the error message, it looks like a syntax issue unrelated to `pipreqs`, so I'm going to close this issue. If you find an example that `pipreqs` fails on, please reopen this issue and provide more details.

**Closed by jonafato** 2017-10-20 19:44 UTC
