### ISSUE TITLE
'pipreqs' is a package and cannot be directly executed

### ISSUE THREAD

**Issue by Makis-Kaniouras** [bndr/pipreqs#139] opened 2018-11-08 13:16 UTC
So I run `python -m pipreqs /path/to/cwd` in a folder that has contents :
```
11/08/2018  12:54 PM    <DIR>          .
11/08/2018  12:54 PM    <DIR>          ..
11/08/2018  02:02 PM    <DIR>          .idea
11/08/2018  11:46 AM               691 app.py
11/08/2018  11:42 AM               531 Dockerfile
11/08/2018  12:54 PM                12 requirements.txt
11/08/2018  11:17 AM    <DIR>          venv
               3 File(s)          1,234 bytes
```
as per dir in cmd. And yet my result is:

> ...Python37\python.exe: No module named pipreqs.__main__; 'pipreqs' is a package and cannot be directly executed

How do I solve this? Is this even related to pipreqs?

**Comment by jonafato** [comment] 2018-11-09 03:07
`pipreqs` does not currently have a [`__main__.py`](https://docs.python.org/3/library/__main__.html). Moving the CLI logic to that file would fix this issue. Open to PRs here.

**Comment by jonafato** [comment] 2018-11-09 03:33
Closing this, as it is a duplicate of #132.

**Closed by jonafato** 2018-11-09 03:33 UTC
Labels: good first issue, help wanted

**Comment by valentinacala** [comment] 2025-02-06 10:40
try with `python -m pipreqs.pipreqs `
